### PR TITLE
Add option to specify custom IP addresses & add option to disable IPv4

### PR DESCRIPTION
**Pull request by marhmm**
Add option to specify a custom IP address as parameter. Can be useful if script is running inside Docker container or you want to read IP address from different sources (for example "ip addr" command with IPv6)

Additionally added option to disable IPv4 if not needed (DS-Lite connection).

Example call with parameter:
`./update.php -IPv4 "x.x.x.x" -IPv6 "x:x:x:x:x:x:x:x"`

### CODE REVIEW

**Comment by geopossachs** [comment]
Hallo @stecklars 
to disable IPv4 is really nice option. My German ISP for example only provide a direct IPv6 access. 
So only the AAAA record make since for my. Please take this improvement into your codebase. :-) 

Have a nice day

**Comment by bohrsty** [comment]
same here, from my provider i only get public ipv6 addresses and ipv4 cg-nat, that isn't reachable from the internet, so an A-record doesn't make any sense...

**Comment by steffenweb** [comment]
https://github.com/steffenweb/dynamic-dns-netcup-api

**Comment by stecklars** [comment]
Hi all,

This is now a new feature in version 4.0 of the script:
https://github.com/stecklars/dynamic-dns-netcup-api/releases/tag/v4.0

I have used your pull request as an inspiration for some of my changes, so thank you a lot :) Unfortunately, I cannot find the time to review pull requests currently. For this reason, I have now also released contributing guidelines which state this. Sorry, that I was not able to merge this at this time. I appreciate your work on this.

**Pull request closed without merging**
